// Bhagavad Gita — 700 verses across 18 chapters.
//
// Sample output showing the structure of data.js
// (This file contains only the first 3 verses as an example)
//
// Generated by build_gita.mjs from multiple open-source datasets:
//
//   Primary (Sanskrit, English, Transliteration):
//     https://ravisiyer.github.io/gita-data/v1/  (Unlicense, public domain)
//     GitHub: https://github.com/gita/gita
//
//   Secondary (Hindi):
//     https://github.com/vedicscriptures/bhagavad-gita  (permissive licenses)
//
// Coverage:
//   ✅ Sanskrit: 100%  (public-domain ancient text)
//   ✅ Transliteration: 100%
//   ✅ English translation: 100%
//   ✅ Word-by-word glosses: 100%
//   ✅ Hindi translation: ~95%  (from Vedicscriptures)
//   ❌ Telugu translation: 0%   (see README or source code for options)
//   ❌ Tags: 0%  (populate manually by topic)
//
// Full output: run `node build_gita.mjs` to generate data.js with all 700 verses

const GITA = [
  {
    chapter: 1,
    verse: 1,
    sanskrit: "धृतराष्ट्र उवाच\n\nधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः।\n\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय।।1.1।।\n ",
    transliteration: "dhṛitarāśhtra uvācha\ndharma-kṣhetre kuru-kṣhetre samavetā yuyutsavaḥ\nmāmakāḥ pāṇḍavāśhchaiva kimakurvata sañjaya\n",
    translation: "Dhritarashtra said: O Sanjaya, what did my sons and the sons of Pandu do on the auspicious battlefield of Kurukshetra?",
    hindi: "धृतराष्ट्र ने कहा - हे संजय! धर्मभूमि कुरुक्षेत्र में एकत्रित हुए और युद्ध की इच्छा रखने वाले मेरे पुत्र तथा पांडु के पुत्र क्या करने लगे?",
    telugu: "",
    word_by_word: [
      "dhṛitarāśhtra: the blind king; uvācha: said",
      "dharma-kṣhetre: on the field of dharma",
      "kuru-kṣhetre: at Kurukshetra",
      "samavetāḥ: assembled",
      "yuyutsavaḥ: desiring to fight",
      "māmakāḥ: my sons",
      "pāṇḍavāḥ: the sons of Pandu",
      "cha: and",
      "eva: certainly",
      "kim: what",
      "akurvata: did they do",
      "sañjaya: O Sanjaya"
    ],
    tags: []
  },
  {
    chapter: 1,
    verse: 2,
    sanskrit: "सञ्जय उवाच\n\nदृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्योधनस्तदा।\n\nआचार्यमुपसङ्गम्य राजा वचनमब्रवीत्।।1.2।।\n ",
    transliteration: "sañjaya uvācha\ndṛiṣhṭvā tu pāṇḍavānīkaṁ vyūḍhaṁ duryodhanastadā\nāchāryamupasaṅgamya rājā vachanamabravīt\n",
    translation: "Sanjaya said: Having observed the Pandava army standing in battle formation, King Duryodhana approached his teacher (Drona) and spoke these words.",
    hindi: "संजय ने कहा - तब व्यूहबद्ध पांडवों की सेना को देखकर राजा दुर्योधन अपने आचार्य के पास जाकर यह बातें कहने लगा।",
    telugu: "",
    word_by_word: [
      "sañjaya: Sanjaya",
      "uvācha: said",
      "dṛiṣhṭvā: observing; seeing",
      "tu: but",
      "pāṇḍava-anīkam: the Pandava army",
      "vyūḍham: standing in formation; arrayed",
      "duryodhana: Duryodhana",
      "tadā: then; at that time",
      "āchāryam: teacher; preceptor",
      "upasaṅgamya: having approached",
      "rājā: the king",
      "vachanam: words; speech",
      "abravīt: spoke"
    ],
    tags: []
  },
  {
    chapter: 1,
    verse: 3,
    sanskrit: "पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम्।\n\nव्यूढां द्रुपदपुत्रेण तव शिष्येण धीमता।।1.3।।\n ",
    transliteration: "paśhyaitāṁ pāṇḍu-putrāṇām āchārya mahatīṁ chamūm\nvyūḍhāṁ drupada-putreṇa tava śhiṣhyeṇa dhīmatā\n",
    translation: "He said: O my teacher, behold this mighty army of the Pandavas, arranged in battle formation by Dhrishtadyumna, the son of Drupad, your intelligent disciple.",
    hindi: "दुर्योधन ने कहा - हे आचार्य! आप पाण्डु के इन पुत्रों की इस महान सेना को देखें। आपके शिष्य, बुद्धिमान द्रुपद पुत्र धृष्टद्युम्न ने इसे व्यूह से सजाया है।",
    telugu: "",
    word_by_word: [
      "paśhya: behold; look",
      "etām: this",
      "pāṇḍu-putrāṇām: of the sons of Pandu",
      "āchārya: O teacher",
      "mahatīm: mighty; great",
      "chamūm: army",
      "vyūḍhām: arrayed; arranged in formation",
      "drupada-putreṇa: by the son of Drupad",
      "tava: your",
      "śhiṣhyeṇa: by the disciple",
      "dhī-matā: by the intelligent one"
    ],
    tags: []
  }
];

if (typeof module !== "undefined") module.exports = GITA;
export default GITA;
