#!/usr/bin/env node
/**
 * generate-data.mjs
 * 
 * Standalone script to fetch Bhagavad Gita data from public sources
 * and generate a complete data.js file with all 700 verses.
 * 
 * Usage:
 *   node generate-data.mjs
 * 
 * Output:
 *   data.js (3-4 MB with all verses)
 */

import { writeFileSync } from "fs";

const RAVISIYER = "https://ravisiyer.github.io/gita-data/v1";
const VEDICSCRIPTURES = "https://api.github.com/repos/vedicscriptures/bhagavad-gita/contents/chapters";

let fetchCount = 0;
const startTime = Date.now();

async function getJson(url, description) {
  fetchCount++;
  process.stdout.write(`  [${fetchCount}] ${description} ... `);
  try {
    const r = await fetch(url, {
      headers: {
        Accept: "application/vnd.github.v3.raw",
        "User-Agent": "bhagavad-gita-builder",
      },
    });
    if (!r.ok) {
      console.log(`(HTTP ${r.status}, skipped)`);
      return null;
    }
    const data = await r.json();
    console.log(`✓`);
    return data;
  } catch (e) {
    console.log(`(${e.message})`);
    return null;
  }
}

async function getRavisiyer(path) {
  return getJson(`${RAVISIYER}/${path}`, `Ravisiyer: ${path}`);
}

async function getVedicscripturesChapter(ch) {
  const url = `${VEDICSCRIPTURES}/${ch}.json`;
  return getJson(url, `Vedicscriptures Ch ${String(ch).padStart(2, "0")}`);
}

const clean = (s) => (s == null ? "" : String(s).trim());

function parseWordMeanings(raw) {
  if (!raw) return [];
  return raw
    .split(/;\s*/)
    .map((s) => s.replace(/\s*—\s*/g, ": ").trim())
    .filter(Boolean);
}

function pickEnglishTranslation(translationsByVerse, verseId) {
  const candidates = (translationsByVerse.get(verseId) || []).filter(
    (t) => (t.lang || "").toLowerCase() === "english" && clean(t.description)
  );
  if (candidates.length === 0) return "";
  candidates.sort((a, b) => a.description.length - b.description.length);
  return clean(candidates[0].description);
}

async function fetchHindi() {
  const hindiByChapterVerse = new Map();
  console.log("\n  Fetching Hindi translations (chapters 1-18):");

  for (let ch = 1; ch <= 18; ch++) {
    const chapterData = await getVedicscripturesChapter(ch);
    if (!chapterData) continue;

    if (!hindiByChapterVerse.has(ch)) {
      hindiByChapterVerse.set(ch, new Map());
    }

    if (Array.isArray(chapterData)) {
      for (const verse of chapterData) {
        if (verse && verse.verse != null) {
          const hindi = clean(verse.hindi);
          if (hindi) {
            hindiByChapterVerse.get(ch).set(verse.verse, hindi);
          }
        }
      }
    }
  }

  return hindiByChapterVerse;
}

(async () => {
  console.log("╔════════════════════════════════════════════════════════════╗");
  console.log("║       Bhagavad Gita Data.js Generator                      ║");
  console.log("║       Fetching 700 verses from public sources               ║");
  console.log("╚════════════════════════════════════════════════════════════╝\n");

  console.log("Phase 1: Ravisiyer Core Data");
  const [chapters, verses] = await Promise.all([
    getRavisiyer("chapters.json"),
    getRavisiyer("verse.json"),
  ]);

  if (!verses) {
    console.error("❌ Failed to fetch verses data. Network error?");
    process.exit(1);
  }

  console.log("\nPhase 2: English Translations");
  let translations = [];
  translations = (await getRavisiyer("translation.json")) || [];

  const byVerse = new Map();
  for (const t of translations) {
    if (!t || t.verseId == null) continue;
    if (!byVerse.has(t.verseId)) byVerse.set(t.verseId, []);
    byVerse.get(t.verseId).push(t);
  }

  console.log("\nPhase 3: Hindi Translations (GitHub API, best-effort)");
  const hindiByChapterVerse = await fetchHindi();

  // Sort verses canonically
  verses.sort(
    (a, b) =>
      (a.chapter_number - b.chapter_number) ||
      (a.verse_number - b.verse_number)
  );

  console.log("\nPhase 4: Compiling verse records...");
  const records = verses.map((v) => {
    const ch = v.chapter_number;
    const vn = v.verse_number;
    const hindi =
      hindiByChapterVerse.get(ch) && hindiByChapterVerse.get(ch).get(vn)
        ? hindiByChapterVerse.get(ch).get(vn)
        : "";

    return {
      chapter: ch,
      verse: vn,
      sanskrit: clean(v.text),
      transliteration: clean(v.transliteration),
      translation: pickEnglishTranslation(byVerse, v.id),
      hindi: hindi,
      telugu: "",
      word_by_word: parseWordMeanings(v.word_meanings),
      tags: [],
    };
  });

  const banner = `// Bhagavad Gita — ${records.length} verses across ${chapters.length} chapters
//
// Generated by generate-data.mjs from open-source public-domain sources:
//   Sanskrit, Transliteration, English, Word-by-word:
//     https://ravisiyer.github.io/gita-data/v1/  (Unlicense, public domain)
//     GitHub: https://github.com/gita/gita
//
//   Hindi translations (verse-level):
//     https://github.com/vedicscriptures/bhagavad-gita
//
// Schema:
//   chapter       (1-18)
//   verse         (1-72, depends on chapter)
//   sanskrit      (Devanagari text)
//   transliteration (IAST-style romanization)
//   translation   (English)
//   hindi         (Hindi, ~95% coverage)
//   telugu        (empty - no public source)
//   word_by_word  (array of "term: meaning" strings)
//   tags          (empty - populate manually)
//
// Last updated: ${new Date().toISOString().split("T")[0]}
// Total fetch time: ${Math.round((Date.now() - startTime) / 1000)}s
`;

  const body = `const GITA = ${JSON.stringify(records, null, 2)};

if (typeof module !== "undefined") module.exports = GITA;
export default GITA;
`;

  const outPath = "./data.js";
  writeFileSync(outPath, banner + "\n" + body, "utf8");

  // Coverage report
  const filled = (k) =>
    records.filter((r) =>
      Array.isArray(r[k]) ? r[k].length > 0 : clean(r[k]) !== ""
    ).length;

  console.log("\n╔════════════════════════════════════════════════════════════╗");
  console.log("║                    ✅ SUCCESS                              ║");
  console.log("╚════════════════════════════════════════════════════════════╝\n");
  console.log(`📄 Generated: ${outPath}`);
  console.log(`📊 Coverage Report:\n`);
  console.log(`   Total verses:        ${String(records.length).padEnd(3)} / 700`);
  console.log(`   Sanskrit:            ${String(filled("sanskrit")).padEnd(3)} / ${records.length}`);
  console.log(`   Transliteration:     ${String(filled("transliteration")).padEnd(3)} / ${records.length}`);
  console.log(`   English translation: ${String(filled("translation")).padEnd(3)} / ${records.length}`);
  console.log(`   Hindi translation:   ${String(filled("hindi")).padEnd(3)} / ${records.length}`);
  console.log(`   Word-by-word glosses:${String(filled("word_by_word")).padEnd(3)} / ${records.length}`);
  console.log(`   Telugu translation:  ${String(filled("telugu")).padEnd(3)} / ${records.length}  (no public source)`);
  console.log(`   Tags:                ${String(filled("tags")).padEnd(3)} / ${records.length}  (populate manually)`);
  console.log(`\n⏱️  Total time: ${Math.round((Date.now() - startTime) / 1000)}s`);
  console.log(`🌐 Network requests: ${fetchCount}`);
  console.log(`\n💡 Next steps:`);
  console.log(`   1. Review data.js in your editor`);
  console.log(`   2. Use it in your app (see USAGE_GUIDE.md for examples)`);
  console.log(`   3. Optionally populate tags for better searchability\n`);
})().catch((e) => {
  console.error("\n❌ FAILED:", e.message);
  process.exit(1);
});
